services:
  mysql:
    image: mysql:8.0
    container_name: oauth2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: agpruebafront
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oauth2-network

  authorization-server:
    build: ./authorization-server
    container_name: oauth2-auth-server
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/agpruebafront?createDatabaseIfNotExist=true
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      # Usamos el endpoint del OKR 5 para saber si el server está vivo
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s # Le damos tiempo a Java para arrancar
    networks:
      - oauth2-network

  resource-server:
    build: ./resource-server
    container_name: oauth2-resource-server
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/agpruebafront?createDatabaseIfNotExist=true
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://authorization-server:9000
    depends_on:
      mysql:
        condition: service_healthy
      authorization-server:
        condition: service_healthy
    networks:
      - oauth2-network

  frontend:
    build: ./ag-prueba-front
    container_name: oauth2-frontend
    ports:
      - "4200:80"
    depends_on:
      resource-server:
        condition: service_started
    networks:
      - oauth2-network

networks:
  oauth2-network:
    driver: bridge
