services:
  mysql:
    image: mysql:8.0
    container_name: oauth2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: agpruebafront
    ports:
      - "3306:3306"
    networks:
      - oauth2-network

  authorization-server:
    build: ./authorization-server
    container_name: oauth2-auth-server
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/agpruebafront?createDatabaseIfNotExist=true
    depends_on:
      - mysql
    networks:
      - oauth2-network

  resource-server:
    build: ./resource-server
    container_name: oauth2-resource-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/agpruebafront?createDatabaseIfNotExist=true
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://authorization-server:9000
    depends_on:
      - authorization-server
      - mysql
    networks:
      - oauth2-network

  frontend:
    build: ./ag-prueba-front
    container_name: oauth2-frontend
    ports:
      - "4200:80"
    depends_on:
      - resource-server
    networks:
      - oauth2-network

networks:
  oauth2-network:
    driver: bridge
